#!/usr/bin/env bash
# Brings up everything needed for a live compliance-dashboard demo:
#   1. bil-test-postgres (Docker) — starts it if stopped, creates it if missing,
#      and creates the table/publication/replication slot on first run only.
#   2. A fresh local Anvil node (state does not persist across restarts, so a
#      fresh node needs a fresh ProofAnchor deploy every time).
#   3. Deploys ProofAnchor.sol to that Anvil node and writes the resulting
#      address into .env.
#   4. Starts proof-service wired to both, in the background.
#
# Logs for anvil and proof-service go to .demo/*.log; PIDs go to .demo/*.pid
# so stop.sh can tear down exactly what this script started.
#
# Safe to re-run: if proof-service or anvil are already running (per the PID
# files), it leaves them alone rather than starting duplicates.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

DEMO_DIR=.demo
mkdir -p "$DEMO_DIR"

PG_CONTAINER=bil-test-postgres
PG_PORT=5433
ANVIL_RPC_URL="http://localhost:8545"
ANVIL_LOG="$DEMO_DIR/anvil.log"
ANVIL_PID_FILE="$DEMO_DIR/anvil.pid"
SERVICE_LOG="$DEMO_DIR/proof-service.log"
SERVICE_PID_FILE="$DEMO_DIR/proof-service.pid"
ENV_FILE=.env

# Anvil's account [0], well-known and public — funds only a throwaway local
# chain, never real value. Fine to hardcode.
ANVIL_DEV_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

is_running() {
  local pid_file="$1"
  [[ -f "$pid_file" ]] && kill -0 "$(cat "$pid_file")" 2>/dev/null
}

echo "==> 1/4  Postgres ($PG_CONTAINER on port $PG_PORT)"
if docker ps --format '{{.Names}}' | grep -qx "$PG_CONTAINER"; then
  echo "    already running"
elif docker ps -a --format '{{.Names}}' | grep -qx "$PG_CONTAINER"; then
  echo "    starting existing container"
  docker start "$PG_CONTAINER" >/dev/null
  sleep 2
else
  echo "    creating container + demo schema (first run)"
  docker run -d --name "$PG_CONTAINER" -e POSTGRES_PASSWORD=testpass -e POSTGRES_DB=bil_test \
    -p "${PG_PORT}:5432" postgres:16 -c wal_level=logical -c max_replication_slots=4 -c max_wal_senders=4 \
    >/dev/null
  echo "    waiting for Postgres to accept connections..."
  until docker exec "$PG_CONTAINER" pg_isready -U postgres >/dev/null 2>&1; do
    sleep 1
  done
  psql -h localhost -p "$PG_PORT" -U postgres -d bil_test -c "
    CREATE TABLE patients (id SERIAL PRIMARY KEY, patient_ref TEXT NOT NULL, diagnosis_code TEXT);
    CREATE PUBLICATION bil_pub FOR TABLE patients;
    SELECT pg_create_logical_replication_slot('bil_slot', 'pgoutput');
  " >/dev/null
fi

echo "==> 2/4  Anvil (local EVM chain, fresh state)"
if is_running "$ANVIL_PID_FILE"; then
  echo "    already running (pid $(cat "$ANVIL_PID_FILE"))"
else
  if lsof -i :8545 -sTCP:LISTEN >/dev/null 2>&1; then
    echo "    ERROR: port 8545 is already in use by a process this script"
    echo "    didn't start (no .demo/anvil.pid). Find and stop it first:"
    echo "      lsof -i :8545 -sTCP:LISTEN"
    exit 1
  fi
  anvil >"$ANVIL_LOG" 2>&1 &
  ANVIL_PID=$!
  echo "$ANVIL_PID" >"$ANVIL_PID_FILE"
  echo "    started (pid $ANVIL_PID), waiting for RPC to come up..."
  for _ in $(seq 1 40); do
    if ! kill -0 "$ANVIL_PID" 2>/dev/null; then
      echo "    ERROR: anvil exited immediately — see $ANVIL_LOG"
      cat "$ANVIL_LOG"
      exit 1
    fi
    cast block-number --rpc-url "$ANVIL_RPC_URL" >/dev/null 2>&1 && break
    sleep 0.5
  done
fi

echo "==> 3/4  Deploying ProofAnchor.sol to Anvil"
DEPLOY_OUTPUT=$(BIL_EVM_RPC_URL="$ANVIL_RPC_URL" \
  BIL_EVM_DEPLOYER_PRIVATE_KEY="$ANVIL_DEV_KEY" \
  cargo run -q -p proof-anchor --example deploy_evm_anchor)
CONTRACT_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep -oE '0x[0-9a-fA-F]{40}' | tail -1)
if [[ -z "$CONTRACT_ADDRESS" ]]; then
  echo "    failed to parse deployed contract address from:"
  echo "$DEPLOY_OUTPUT"
  exit 1
fi
echo "    deployed at $CONTRACT_ADDRESS"

cat >"$ENV_FILE" <<EOF
# Regenerated by start.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — values only valid
# for the Anvil instance this script started (pid $(cat "$ANVIL_PID_FILE")).
BIL_EVM_RPC_URL=$ANVIL_RPC_URL
BIL_EVM_DEPLOYER_PRIVATE_KEY=$ANVIL_DEV_KEY
BIL_EVM_PRIVATE_KEY=$ANVIL_DEV_KEY
BIL_EVM_CONTRACT_ADDRESS=$CONTRACT_ADDRESS
EOF
echo "    wrote $ENV_FILE"

echo "==> 4/4  proof-service"
if is_running "$SERVICE_PID_FILE"; then
  echo "    already running (pid $(cat "$SERVICE_PID_FILE"))"
else
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
  # stdbuf disables stdout buffering so `tail -f` shows lines live during a
  # demo instead of only flushing once the buffer fills or the process exits.
  # RUST_LOG is required because tracing_subscriber::fmt::init() emits
  # nothing at all (not even warnings) with no filter set.
  RUST_LOG="${RUST_LOG:-proof_service=info}" \
  stdbuf -oL -eL cargo run -q -p proof-service -- \
    --pg-host localhost --pg-port "$PG_PORT" --pg-user postgres --pg-password testpass --pg-dbname bil_test \
    --pg-slot bil_slot --pg-publication bil_pub \
    --source-id "postgres:patients" \
    --anchor-backend evm \
    >"$SERVICE_LOG" 2>&1 &
  echo $! >"$SERVICE_PID_FILE"
  echo "    started (pid $!), waiting for it to come up..."
  until curl -s -o /dev/null "http://127.0.0.1:8080/"; do
    sleep 0.5
  done
fi

echo
echo "Ready:"
echo "  Live feed          http://localhost:8080/"
echo "  Compliance overview http://localhost:8080/compliance"
echo "  proof-service log   tail -f $SERVICE_LOG"
echo "  anvil log           tail -f $ANVIL_LOG"
echo
echo "Insert a demo row with:"
echo "  PGPASSWORD=testpass psql -h localhost -p $PG_PORT -U postgres -d bil_test -c \\"
echo "    \"INSERT INTO patients (patient_ref, diagnosis_code) VALUES ('DEMO-001', 'J45.909');\""
echo
echo "When done: ./stop.sh"
